# Generated by Django 4.2.5 on 2023-09-14 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(default='1ec8912359e5c54c4a5bee95b28d75b94eb3', max_length=36, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=10)),
                ('photo', models.ImageField(upload_to='profile/photo')),
                ('message', models.CharField(blank=True, default='Hey there! I am using ChatDrop', max_length=100)),
                ('bio', models.CharField(blank=True, default='', max_length=2000)),
                ('interest', models.TextField(blank=True, default='')),
                ('website', models.CharField(blank=True, default='', max_length=1000)),
                ('location', models.CharField(blank=True, default='', max_length=25)),
                ('acc_type', models.CharField(choices=[('ADMIN', 'Admin'), ('DEPARTMENT', 'Department'), ('STUDENT', 'Student')], default='ADMIN', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('enc_key', models.TextField(blank=True, default='')),
                ('msg_token', models.TextField(blank=True, default='')),
                ('is_admin', models.BooleanField(default=False)),
                ('terms_conditions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=500)),
                ('device', models.CharField(default='', max_length=20)),
                ('os', models.CharField(default='', max_length=20)),
                ('browser', models.CharField(default='', max_length=20)),
                ('created_on', models.DateTimeField(default=None)),
                ('active_until', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
